name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # Sostituisci "main" con il tuo branch principale se necessario

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Assicurati che la versione corrisponda a quella richiesta dal progetto

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Cambia con il comando di build del tuo progetto

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
